---
- name: Create Kubernetes namespaces
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Ensure namespaces exist
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ item }}"
        state: present
      loop:
        - jenkins
        - elastic
        - logstash
